spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: letsky
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/wechat?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
logging:
  file: wechat-dev.log
wx:
  miniapp:
    config:
      appid: wx2d43064410c4d0e0
      secret: 7d9d15de36920c2709e0702528cd2a40
qiniu:
  access-key: dNM2QQ0Y_tA5f4dVeIy9pYBi3PMKYczXJoF8bJiz
  secret-key: _E205cCsUnO88Q6Xb2AzlquAvFgGUyU0t0wZ7lRn
  bucket: wechat-dev
  domain: http://img-dev.letsky.cn/